services:
  backend:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: fastapi_backend
    restart: unless-stopped
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    volumes:
      - .:/app # Mount current directory to /app in container for live code reload
      - /app/.venv # Prevent host .venv from overwriting container .venv
    environment:
      - DATABASE_URL=postgresql+asyncpg://news_user:12345678@db:5432/news_db
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      db:
        condition: service_healthy # Wait for the DB to be ready
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://api.nuze.dpdns.org
    container_name: react_frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    networks:
      - app_network
  db:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: postgres_pgvector_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: news_user
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: news_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U news_user -d news_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  ollama:
    image: ollama/ollama
    container_name: ollama_server
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./scripts/init/init_ollama.sh:/init_ollama.sh
      - ./scripts/init/ollama-models/news-cls-modfile:/news-cls-modfile:ro
      - ./scripts/init/ollama-models/news-combiner-modfile:/news-combiner-modfile:ro
      - ./scripts/init/ollama-models/news-summarizer-modfile:/news-summarizer-modfile:ro
    entrypoint: /bin/sh
    command: /init_ollama.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

    networks:
      - app_network

volumes:
  postgres_data: # Define a named volume for data persistence
  ollama_data:


networks:
  app_network:
    driver: bridge
